---
- hosts: databases
  become: true
  tasks:
    - name: install apache
      yum:
        name: httpd
        state: latest
    - name:
      file:
        state: touch
        path: /var/www/html/index.html
    - name: If line not there add it
      lineinfile:
        state: present
        dest: /var/www/html/index.html
        line: Hostname={{ ansible_hostname }}
    - name: restart apache
      service:
        name: httpd
        state: reloaded
        enabled: yes