---
- hosts: databases
  become: true
  vars:
    description: "{{ ansible_hostname }}"
  tasks:
    - name: write the index file
      template: src=../templates/template.j2 dest=/var/www/html/index.html
      notify:
        - restart httpd
    - name: ensure apache is running
      service: name=httpd state=started
  handlers:
    - name: restart httpd
      service: name=httpd state=restarted
