---
- hosts: databases
  become: true
  vars:
    database_name_here: wordpress
    username_here: wordpress
    password_here: mypassword
    dbhost_here: host2
  tasks:
  - name: install php for wordpress
    yum: name={{item}}
    with_items:
      - php
      - php-gd
      - php-pear
      - php-mysql
  - name: restart httpd
    service: name=httpd state=restarted
  - unarchive:
      src: https://wordpress.org/latest.tar.gz
      dest: /tmp/
      remote_src: true
  - name: remove html folder
    command: /usr/bin/rm -rf /var/www/html
  - name: move wordpress
    command: /usr/bin/mv /tmp/wordpress /var/www/html
  - name: copy template
    template: src=../templates/wp-config.j2 dest=/var/www/html/wp-config.php
